package com.embabel.template.injected;

import com.embabel.agent.api.common.Ai;
import jakarta.validation.constraints.Pattern;
import org.springframework.stereotype.Component;

/**
 * Demonstrates injecting Embabel's {@link Ai} interface into a regular Spring component.
 * <p>
 * <b>Key Embabel Concept — Ai Injection:</b> The {@link Ai} interface is the gateway to
 * all AI functionality in Embabel. It can be injected into any Spring-managed bean
 * (not just {@code @Agent} classes) via standard constructor injection. This allows
 * any part of your application — controllers, services, scheduled tasks — to perform
 * LLM operations without being an agent.
 * <p>
 * This differs from using {@code Ai} inside an {@code @Action} method, where the
 * framework provides a context-aware instance tied to the current agent process.
 * Here, the injected {@code Ai} operates independently of any agent execution.
 *
 * @param ai Embabel AI helper, injected by Spring's constructor injection
 * @see com.embabel.agent.api.common.Ai
 * @see com.embabel.agent.api.common.PromptRunner
 */
@Component
public record InjectedDemo(Ai ai) {

    /**
     * Domain object for a fictional animal, demonstrating JSR-380 validation on LLM output.
     * <p>
     * <b>Key Embabel Concept — Validation:</b> Embabel automatically validates objects
     * created by {@code createObject()} / {@code creating().fromPrompt()} against JSR-380
     * (Bean Validation) annotations. If the LLM produces output that violates a constraint,
     * the framework retries the generation (with configurable retry policy). This provides
     * a powerful guardrail mechanism to ensure LLM output conforms to business rules.
     * <p>
     * In this example, the {@code @Pattern} annotation on {@code species} requires it to
     * contain "ox". If the LLM generates "Dragon" as the species, validation fails and
     * the framework automatically retries until a valid result is produced.
     *
     * @param name the animal's name
     * @param species the animal's species (must contain "ox" per the validation constraint)
     */
    public record Animal(
            String name,
            @Pattern(regexp = ".*ox.*", message = "Species must contain 'ox'")
            String species) {
    }

    /**
     * Invents a fictional animal using the Embabel {@code Creating} fluent API.
     * <p>
     * <b>Key Embabel Concept — Creating API:</b> The {@code creating()} method on
     * {@link com.embabel.agent.api.common.PromptRunner} returns a
     * {@code PromptRunner.Creating} builder that provides:
     * <ul>
     *   <li>{@code withExample(description, value)} — adds typed examples to the prompt,
     *       serialized as JSON. Good and bad examples help the LLM understand the expected format.</li>
     *   <li>{@code withPropertyFilter()} / {@code withProperties()} / {@code withoutProperties()}
     *       — control which record fields the LLM should populate.</li>
     *   <li>{@code withValidation()} / {@code withoutValidation()} — toggle JSR-380 validation.</li>
     *   <li>{@code fromPrompt()} — sends the prompt and returns the deserialized, validated object.</li>
     * </ul>
     * <p>
     * <b>withId():</b> Sets an interaction ID on the {@code PromptRunner} for tracing and
     * observability. When the observability module is enabled, this ID appears in traces.
     * <p>
     * <b>withDefaultLlm():</b> Uses the platform's default model (configured via
     * {@code embabel.models.defaultLlm} in application.yml).
     *
     * @return a validated {@link Animal} instance generated by the LLM
     */
    public Animal inventAnimal() {
        return ai
                // withDefaultLlm(): Uses the default model configured in application.yml
                .withDefaultLlm()
                // withId(): Sets an interaction ID for tracing/observability
                .withId("invent-animal")
                // creating(): Enters the typed object creation fluent API
                .creating(Animal.class)
                // withExample(): Adds examples serialized as JSON to guide the LLM.
                // Good examples show the desired format; bad examples show what to avoid.
                .withExample("good example", new Animal("Fluffox", "Magicox"))
                .withExample("bad example: does not pass validation", new Animal("Sparky", "Dragon"))
                // fromPrompt(): Sends the prompt, deserializes the response into Animal,
                // and validates it against JSR-380 annotations (retrying if needed).
                .fromPrompt("""
                        You just woke up in a magical forest.
                        Invent a fictional animal.
                        The animal should have a name and a species.
                        """);
    }
}
